{"message": {"message": "SignalException: Process 14638 got signal: 1", "extraInfo": {"py_callstack": "Traceback (most recent call last):\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 346, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/run.py\", line 794, in main\n    run(args)\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/run.py\", line 785, in run\n    elastic_launch(\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 134, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py\", line 241, in launch_agent\n    result = agent.run()\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py\", line 129, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 723, in run\n    result = self._invoke_run(role)\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py\", line 864, in _invoke_run\n    time.sleep(monitor_interval)\n  File \"/home/junyi/.conda/envs/mainpyenv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py\", line 62, in _terminate_process_handler\n    raise SignalException(f\"Process {os.getpid()} got signal: {sigval}\", sigval=sigval)\ntorch.distributed.elastic.multiprocessing.api.SignalException: Process 14638 got signal: 1\n", "timestamp": "1697361285"}}}